config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  devise_for :users
  resource :stylesheets, except: [:new, :update, :create] do
    collection do
      patch :create_update
    end
  end

end

app/models/stylesheet.rb
require 'w3c_validators'
class Stylesheet < ActiveRecord::Base

  include W3CValidators

  FAMILY_LIST =[ 'Sans-Serif', 'Arial, sans-serif', 'Helvetica, sans-serif',
                 'Gill Sans, sans-serif', 'Lucida, sans-serif', 'Helvetica Narrow, sans-serif',
                 'sans-serif', 'Times, serif', 'Times New Roman, serif',
                 'Palatino, serif', 'Bookman, serif', 'New Century Schoolbook, serif',
                 'serif', 'Courier New, monospace', 'Courier, monospace', 'Lucidatypewriter, monospace',
                 'Fixed, monospace', 'monospace']

  DEFAULT_FAMILY = "Sans-Serif"
  DEFAULT_SIZE = 12
  DEFAULT_COLOR = '#3c3c3c'

  validate :check_custom_css, :if => Proc.new{|f| f.custom.present? } 

  def initialize(args=nil)
    super
    self.family = DEFAULT_FAMILY
    self.size = DEFAULT_SIZE
    self.color = DEFAULT_COLOR
  end

  private 
  def check_custom_css
    validator = CSSValidator.new
    results = validator.validate_text(self.custom)
    errors.add(:custom, "Invalid custom css text.") if results.errors.length > 0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_one :stylesheet

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_filter :authenticate_user!

  protected

  # Never trust parameters from the scary internet, only allow the white list through.
  # This is for user permitted parameters for sign_up
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!, only:[:index]

  # This is the root home page action for all user.
  def index
  end
end

app/controllers/stylesheets_controller.rb
class StylesheetsController < ApplicationController
  before_action :set_stylesheet, only: [:show, :edit, :create_update, :destroy]
  skip_before_action :authenticate_user!, only: [:show]

  # GET /stylesheets/1
  # GET /stylesheets/1.json
  def show
    respond_to do |format|
      format.css
    end
  end

  # GET /stylesheets/1/edit
  def edit
  end

  def create_update
    if @stylesheet.update(stylesheet_params)
      render text: "", status: :ok
    else
      render json: @stylesheet.errors, status: :unprocessable_entity 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stylesheet
      @stylesheet = current_user.present? ? Stylesheet.find_or_create_by({user_id: current_user.id}) : Stylesheet.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stylesheet_params
      params.require(:stylesheet).permit(:family, :size, :color, :t, :custom)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrasing_helper.rb
module PhrasingHelper
  # You must implement the can_edit_phrases? method.
  # Example:
  #
  # def can_edit_phrases?
  #  current_user.is_admin?
  # end

  def can_edit_phrases?
    current_user.present?
  end
end

app/helpers/stylesheets_helper.rb
module StylesheetsHelper
end

app/views/home/index.html.erb
<h2> <%= phrase('Welcome to User page customization') %></h2>
<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Page Customizing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag(stylesheets_path(current_user, format: :css), id: 'css') %>

</head>
<body>
  <nav class="navbar navbar-static-top navbar-default">
    <div class="container">
      <div class="navbar-header">
      	<%= link_to 'User Page Customizing', root_path %>
      </div>
      <div id="nav" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">          
          <%= render partial: "shared/links" %> 
        </ul>

      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, class: "alert alert-#{name}") do%>
      <%=msg%>
      <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%end%>
<% end %>

</body>
</html>

app/views/shared/_links.html.erb
<% if current_user.present? %>
  <li> <%= link_to 'Customize Page', edit_stylesheets_path %></li>
  <li> <%= link_to 'Log out', destroy_user_session_path, method: :delete, id: "logout" %></li>
<% else %>
  <li> <%= link_to 'Create User', new_user_registration_path %></li>
  <li> <%= link_to 'Sign In', new_user_session_path %></li>
<% end %>

app/views/stylesheets/_form.html.erb
<%= form_for(@stylesheet, url: {action: "create_update"}, method: 'Patch', :html => { id: "css_form"} ) do |f| %>
  <div class="field">
    <%= f.label :family %><br>
    <%= f.select :family, Stylesheet::FAMILY_LIST, selected: @stylesheet.family %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.select :size, (5..30), selected: @stylesheet.size %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color, class: 'colorpicker', value: @stylesheet.color  %>
  </div>
  <div class="field">
    <%= f.label :custom %><br>
    <%= f.text_area :custom %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/stylesheets/edit.html.erb
<h1>Editing Stylesheet</h1>

<%= render 'form' %>

app/views/stylesheets/show.css.erb
html, body{
  font-family: <%= @stylesheet.family %> !important;
  font-size: <%= @stylesheet.size %>px;
  color: <%= @stylesheet.color %> ;
}
<%= @stylesheet.custom %>